import pyPLS
import numpy as np

if __name__ == '__main__':
    Xt, Z, Yt = pyPLS.simulateData(50, 5, 1000, 10., signalToNoise=50.)

    print("Simulated data has 5 components")
    print("Testing PCA...")
    out = pyPLS.pca(Xt, 4)
    out.summary()
    print()
    print()
    print("Testing noPLS1...")
    out = pyPLS.nopls1(Xt, Yt[:, 0], cvfold=7)
    out.summary()
    print()
    print()
    print("Testing noPLS2 with one column in Y...")
    out = pyPLS.nopls2(Xt, Yt[:, 0], cvfold=7)
    out.summary()
    print()
    print()
    print("Testing noPLS2 with two columns in Y...")
    out = pyPLS.nopls2(Xt, Yt[:, 0:2], cvfold=7)
    out.summary()
    print()
    print()
    print("Testing PLS1 with 3 components...")
    out = pyPLS.pls1(Xt, Yt[:, 0], 3, cvfold=7)
    out.summary()
    print()
    print()
    print("Testing PLS2 with 3 components...")
    out = pyPLS.pls2(Xt, Yt[:, 0:2], 3, cvfold=7)
    out.summary()
    print()

    print("Testing noPLS2-DA...")
    Ybar = np.mean(Yt[:,0])
    Group1 = np.where(Yt[:,0] < Ybar)
    Group2 = np.where(Yt[:,0] >=Ybar)
    Dummy = np.zeros((50,1))
    Dummy[Group2,:] = 1
    out = pyPLS.nopls2(Xt,Dummy, scaling=1., cvfold=7)
    out.summary()