import pyPLS

if __name__ == '__main__':
    Xt, Z, Yt = pyPLS.simulateData(50, 5, 1000, 10., signalToNoise=1.0)
    print("Simulated data has 5 components")
    print("Testing PCA...")
    out = pyPLS.pca(Xt, 4)
    out.summary()
    print()
    print()
    print("Testing noPLS1...")
    out = pyPLS.nopls1(Xt, Yt[:, 0], cvfold=7)
    out.summary()
    print()
    print()
    print("Testing noPLS2 with one column in Y...")
    out = pyPLS.nopls2(Xt, Yt[:, 0], cvfold=7)
    out.summary()
    print()
    print()
    print("Testing noPLS2 with two columns in Y...")
    out = pyPLS.nopls2(Xt, Yt[:, 0:2], cvfold=7)
    out.summary()
    print()
    print()
    print("Testing PLS1 with 3 components...")
    out = pyPLS.pls1(Xt, Yt[:, 0], 3, cvfold=7)
    out.summary()
    print()
    print()
    print("Testing PLS2 with 3 components...")
    out = pyPLS.pls2(Xt, Yt[:, 0:2], 3, cvfold=7)
    out.summary()
    print()
